---
- name: Deploying Java-Project
  hosts: all
  vars:
    mysql_socket:
      RedHat: /var/lib/mysql/mysql.sock
      Debian: /var/run/mysqld/mysqld.sock
    distro:
      RedHat: python3-PyMySQL
      Debian: python3-pymysql
    javajdk:
      RedHat: java-17-openjdk
      Debian: openjdk-17-jdk
    packages:
      - mariadb-server
      - maven
      - git
    db_pass: password

  tasks:
    - name: Install JDK {{ javajdk[ansible_os_family] }}
      package:
        name: "{{ javajdk[ansible_os_family] }}"
        state: present

    - name: Install Packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

    - name: Install Python-MySQL
      package:
        name: "{{ distro[ansible_os_family] }}"
        state: present

    - name: Start the DB service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Secure Mysql/Mariadb Installation
      mysql_user:
        name: root
        password: "{{ db_pass }}"
        login_unix_socket: "{{ mysql_socket[ansible_os_family] }}"
        priv: '*.*:ALL,GRANT'
        check_implicit_admin: yes
        host: localhost
        login_user: root
        login_password: "{{ db_pass }}"

    - name: Create reviewdb Database
      mysql_db:
        name: reviewdb
        state: present
        login_user: root
        login_password: "{{ db_pass }}"

    - name: Creating DB user admin
      mysql_user:
        name: admin
        password: "{{ db_pass }}"
        host: "%"
        priv: 'reviewdb.*:ALL,GRANT'
        state: present
        login_user: root
        login_password: "{{ db_pass }}"

    - name: Clone Source Code from Github
      git:
        repo: 'https://github.com/YagneshTrainer/reviewapp.git'
        dest: /tmp/reviewapp
        force: yes
        update: yes

    - name: Modifying the application.properties
      template:
        src: application.properties.j2
        dest: /tmp/reviewapp/src/main/resources/application.properties

    - name: Copy DB Server File
      template:
        src: 50-server.cnf.j2
        dest: /etc/mysql/mariadb.conf.d/50-server.cnf
      when: ansible_os_family == "Debian"

    - name: Restart Mysql service on {{ ansible_host }}
      service:
        name: mariadb
        state: restarted # Very important to restart on Debian systems, redhat works fine.

    - name: Buliding artifact
      command: sudo mvn clean install
      args:
        chdir: /tmp/reviewapp

    - name: Create reviewapp Document Root
      file:
        path: /opt/reviewapp
        state: directory
        mode: 0777

    - name: Copy the artifact
      command: mv /tmp/reviewapp/target/ReviewApp-0.0.1-SNAPSHOT.jar /opt/reviewapp/ReviewApp-0.0.1-SNAPSHOT.jar

    - name: Create Service file for systemd
      copy:
        dest: /etc/systemd/system/reviewapp.service
        content: |
          [Unit]
          Description=Spring Boot ReviewApp
          After=network.target

          [Service]
          User=root
          ExecStart=/usr/bin/java -jar /opt/reviewapp/ReviewApp-0.0.1-SNAPSHOT.jar
          SuccessExitStatus=143
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target


    - name: Start and enable the reviewapp service
      service:
        name: reviewapp
        state: started
        enabled: yes

    - name: Setup Firewall for Java port
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
        immediate: yes
      when: ansible_os_family == "RedHat"
