pipeline {
    agent any

    stages {
        stage('Deploy to EKS') {
            steps {
                sh """
                kubectl set image deployment/reviewapp \
                reviewapp=innovativeacademy/reviewapp:${BUILD_NUMBER}
                """
            }
        }
    }
}
